version: '3'
services:
  recorder:
    image: "robotastic/trunk-recorder:latest"
    privileged: true
    command: ["trunk-recorder","--config=/app/config.json"]
    volumes:
      - .:/app
      - /dev/bus/usb:/dev/bus/usb