version: '3'
services:
  recorder:
    image: "robotastic/trunk-recorder:latest"
    privileged: true
    command: ["recorder","--config=/app/config/config.json"]
    volumes:
      - ./media:/app/media
      - ./config:/app/config
      - /dev/bus/usb:/dev/bus/usb